# Generated by Django 5.2.7 on 2025-10-15 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'indexes': [models.Index(fields=['name'], name='hello_app_c_name_07df08_idx')],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
                ('equipment', models.CharField(max_length=50, verbose_name='Комплектация')),
                ('colour', models.CharField(max_length=11, verbose_name='Цвет')),
                ('categories_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.categories')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('father_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.car')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'ordering': ['last_name', 'first_name', 'father_name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=50, verbose_name='Должность')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['salary'],
                'indexes': [models.Index(fields=['post'], name='hello_app_p_post_8baa3d_idx'), models.Index(fields=['salary'], name='hello_app_p_salary_ede1d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('father_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.post')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
                'ordering': ['last_name', 'first_name', 'father_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.car')),
                ('costumer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.costumer')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.seller')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['price'],
            },
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['name'], name='hello_app_c_name_c6341e_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['price'], name='hello_app_c_price_c056ef_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['colour'], name='hello_app_c_colour_17a72b_idx'),
        ),
        migrations.AddIndex(
            model_name='costumer',
            index=models.Index(fields=['first_name'], name='hello_app_c_first_n_9780b2_idx'),
        ),
        migrations.AddIndex(
            model_name='costumer',
            index=models.Index(fields=['last_name'], name='hello_app_c_last_na_98c92d_idx'),
        ),
        migrations.AddIndex(
            model_name='costumer',
            index=models.Index(fields=['phone_number'], name='hello_app_c_phone_n_f28442_idx'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['first_name'], name='hello_app_s_first_n_118620_idx'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['last_name'], name='hello_app_s_last_na_e4ee92_idx'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['phone_number'], name='hello_app_s_phone_n_ebf791_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['price'], name='hello_app_o_price_b521a1_idx'),
        ),
    ]
