# Generated by Django 5.2.6 on 2025-09-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['surname', 'name'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.RemoveField(
            model_name='author',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='book',
            name='id_author',
        ),
        migrations.AddField(
            model_name='author',
            name='bitrhday',
            field=models.DateField(default='1999-02-02', verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='author',
            name='desc',
            field=models.CharField(default='dwa', verbose_name='hgjg'),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Названиие'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['surname'], name='hello_app_a_surname_eefb75_idx'),
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(condition=models.Q(('desc', 'Жив')), fields=('surname', 'bio'), name='unique_surname_bio'),
        ),
    ]
