# Generated by Django 5.2.6 on 2025-09-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0002_alter_author_options_remove_author_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='desc',
            field=models.CharField(default='No', verbose_name='Жив или мертв'),
        ),
    ]
