# Generated by Django 5.2.8 on 2025-11-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0002_alter_order_car_alter_order_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фотография'),
        ),
    ]
