# Generated by Django 5.2.8 on 2025-11-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0003_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='sellers/', verbose_name='Фотография'),
        ),
    ]
