# Generated by Django 5.2.6 on 2025-10-01 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0003_alter_author_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
                ('equipment', models.CharField(max_length=50, verbose_name='Комплектация')),
                ('colour', models.CharField(max_length=11, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('father_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'ordering': ['last_name', 'first_name', 'father_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=50, verbose_name='Должность')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['salary'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('father_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
                'ordering': ['last_name', 'first_name', 'father_name'],
            },
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='id_publisher',
        ),
        migrations.AddIndex(
            model_name='categories',
            index=models.Index(fields=['name'], name='hello_app_c_name_07df08_idx'),
        ),
        migrations.AddField(
            model_name='car',
            name='categories_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.categories'),
        ),
        migrations.AddField(
            model_name='costumer',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.car'),
        ),
        migrations.AddField(
            model_name='order',
            name='costumer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.costumer'),
        ),
        migrations.AddField(
            model_name='costumer',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.order'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post'], name='hello_app_p_post_8baa3d_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['salary'], name='hello_app_p_salary_ede1d7_idx'),
        ),
        migrations.AddField(
            model_name='seller',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.post'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.seller'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['name'], name='hello_app_c_name_c6341e_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['price'], name='hello_app_c_price_c056ef_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['colour'], name='hello_app_c_colour_17a72b_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['equipment'], name='hello_app_c_equipme_45c6ec_idx'),
        ),
        migrations.AddIndex(
            model_name='costumer',
            index=models.Index(fields=['first_name'], name='hello_app_c_first_n_9780b2_idx'),
        ),
        migrations.AddIndex(
            model_name='costumer',
            index=models.Index(fields=['last_name'], name='hello_app_c_last_na_98c92d_idx'),
        ),
        migrations.AddIndex(
            model_name='costumer',
            index=models.Index(fields=['phone_number'], name='hello_app_c_phone_n_f28442_idx'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['first_name'], name='hello_app_s_first_n_118620_idx'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['last_name'], name='hello_app_s_last_na_e4ee92_idx'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['phone_number'], name='hello_app_s_phone_n_ebf791_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['price'], name='hello_app_o_price_b521a1_idx'),
        ),
    ]
