# Generated by Django 5.2.8 on 2025-11-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0004_seller_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2024, verbose_name='Год выпуска'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['year'], name='hello_app_c_year_e1a8b5_idx'),
        ),
    ]
