# Generated by Django 5.2.7 on 2025-10-08 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0004_car_categories_costumer_order_post_seller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumer',
            name='order_id',
        ),
    ]
